### ISSUE TITLE
Sección de equipo

### ISSUE THREAD

**Issue by juanyepesu2** [Grupo-42-Mision-TIC-2022/Semana-1-42#4]
Dividir el ancho del sitio entre el número de participantes del equipo e incluir junto con cada uno una foto o imagen, el nombre y algún dato como la institución educativa, edad, pasatiempo, entre otros. El elemento donde están los servicios debe de tener un id=”team”

**Comment by DiMoGal** [comment]
Vale muchas gracias Juan, si quieres me envías tu información :)

**Comment by juanyepesu2** [comment]
Profesión: Médico
Institución educativa: UdeA
Edad: 42 años
Pasatiempo: Cine y las nuevas tecnologías

**Comment by DiMoGal** [comment]
Gracias Juan, que pases una feliz noche
